---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: debug cyberark client cert
      debug:
        msg: "{{ CYBERARK_CLIENT_CERT }}"

    - name: debug cyberark priv key
      debug:
        msg: "{{ CYBERARK_PRIV_KEY }}"

    - name: print client cert
      shell: cat "{{ CYBERARK_CLIENT_CERT }}"
      register: actual_cert

    - name: print priv key
      shell: cat "{{ CYBERARK_PRIV_KEY }}"
      register: actual_key

    - name: debug cert
      debug:
        var: actual_cert

    - name: debug key
      debug:
        var: actual_key
