---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: debug cyberark client cert
      debug:
        msg: "{{ lookup('env','CYBERARK_CLIENT_CERT') }}"

    - name: debug cyberark priv key
      debug:
        msg: "{{ lookup('env','CYBERARK_PRIV_KEY') }}"
